spring:
  mail:
    host: smtpout.secureserver.net
    port: 465
    username: info@stockviewsindia.com
    password: sony12345
    protocol: smtp
    properties:
      mail:
        smtp:
          timeout: 25000
          auth: true
          starttls:
            enable: true

#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: testAutomation

application:
  name: ASAPP Automation
  shortName: ASAPP Automation

paths:
  integration: /auto-api-ui-testng/build/test-results/
  extentReport: /auto-api-ui-testng/build/extent-reports/
  emailReport: /auto-api-ui-testng/build/email-reports/
  integrationJunit: /auto-api-ui-junit/build/test-results/
  extentReportJunit: /auto-api-ui-junit/build/email-reports/
  emailReportJunit: /auto-api-ui-junit/build/email-reports/

email:
  from: info@stockviewsindia.com
  toQa: anbumaran@hotmail.com
  to: anbumaran@hotmail.com, anbumaran@yahoo.com
